export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headLine: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart : false,
    img: require('../../images/svg-6.svg'),
    alt: 'btc',
    dark: false,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headLine: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you nedd is an internet connection and a phone or computer.',
    buttonLabel: 'Learn More',
    imgStart : true,
    img: require('../../images/svg-4.svg'),
    alt: 'btc-tree',
    dark: false,
    primary: true,
    darkText: true,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headLine: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes. All you nedd to do is add your information and you\'re ready to go.',
    buttonLabel: 'Start Now',
    imgStart : true,
    img: require('../../images/svg-8.svg'),
    alt: 'Card',
    dark: false,
    primary: true,
    darkText: true,
}
